# Generated by Django 5.1.7 on 2025-04-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_availability',
            field=models.BooleanField(default=True, verbose_name='наличие в библиотеке'),
        ),
    ]
